Vdmt_Ls02/Vdmt_Ls02/Models/ErrorViewModel.cs
namespace Vdmt_Ls02.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Vdmt_Ls02/Vdmt_Ls02/Controllers/VdmtHomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Vdmt_Ls02.Models;

namespace Vdmt_Ls02.Controllers
{
    public class VdmtHomeController : Controller
    {
        private readonly ILogger<VdmtHomeController> _logger;

        public VdmtHomeController(ILogger<VdmtHomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult VdmtIndex()
        {
            return View();
        }

        public IActionResult VdmtAbout()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Vdmt_Ls02/Vdmt_Ls02/Controllers/VdmtProductController.cs
using Microsoft.AspNetCore.Mvc;

namespace Vdmt_Ls02.Controllers
{
    public class VdmtProductController : Controller
    {
        public IActionResult Vdmt()
        {
            ViewData["messageData"] = "Du lieu tu ViewData";
            ViewBag.messageBag = "Du lieu tu ViewBag";
            TempData["TempData"] = "Du lieu tu TempData";
            return View();
        }
    }
}

Vdmt_Ls02/Vdmt_Ls02/Views/Shared/_VdmtLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Vdmt_Ls02</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Vdmt_Ls02.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="VdmtHome" asp-action="VdmtIndex">Vdmt_Ls02</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VdmtHome" asp-action="VdmtIndex">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VdmtHome" asp-action="VdmtAbout">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VdmtProduct" asp-action="Vdmt">Product</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Vdmt_Ls02 - <a asp-area="" asp-controller="VdmtHome" asp-action="VdmtAbout">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Vdmt_Ls02/Vdmt_Ls02/Views/VdmtProduct/Vdmt.cshtml
@{
    ViewData["Title"] = "Vdmt";
}

<h1>Du lieu tu controller</h1>
<hr/>
<h2>
    @ViewData["messageData"]
    <hr/>
    @ViewBag.messageData
    <hr/>
    @TempData["messageData"]
</h2>